/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsSyncRouteImport } from './routes/settings.sync'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsDashboardRouteImport } from './routes/settings.dashboard'
import { Route as SettingsBackupRouteImport } from './routes/settings.backup'
import { Route as SettingsArchiveRouteImport } from './routes/settings.archive'
import { Route as ApiWebhooksBatteryRouteImport } from './routes/api/webhooks/battery'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSyncRoute = SettingsSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDashboardRoute = SettingsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBackupRoute = SettingsBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchiveRoute = SettingsArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => SettingsRoute,
} as any)
const ApiWebhooksBatteryRoute = ApiWebhooksBatteryRouteImport.update({
  id: '/api/webhooks/battery',
  path: '/api/webhooks/battery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/archive': typeof SettingsArchiveRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/dashboard': typeof SettingsDashboardRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/webhooks/battery': typeof ApiWebhooksBatteryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/archive': typeof SettingsArchiveRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/dashboard': typeof SettingsDashboardRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/settings': typeof SettingsIndexRoute
  '/api/webhooks/battery': typeof ApiWebhooksBatteryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/archive': typeof SettingsArchiveRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/dashboard': typeof SettingsDashboardRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/webhooks/battery': typeof ApiWebhooksBatteryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/settings/archive'
    | '/settings/backup'
    | '/settings/dashboard'
    | '/settings/notifications'
    | '/settings/sync'
    | '/settings/'
    | '/api/webhooks/battery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/archive'
    | '/settings/backup'
    | '/settings/dashboard'
    | '/settings/notifications'
    | '/settings/sync'
    | '/settings'
    | '/api/webhooks/battery'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/settings/archive'
    | '/settings/backup'
    | '/settings/dashboard'
    | '/settings/notifications'
    | '/settings/sync'
    | '/settings/'
    | '/api/webhooks/battery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ApiWebhooksBatteryRoute: typeof ApiWebhooksBatteryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/sync': {
      id: '/settings/sync'
      path: '/sync'
      fullPath: '/settings/sync'
      preLoaderRoute: typeof SettingsSyncRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/dashboard': {
      id: '/settings/dashboard'
      path: '/dashboard'
      fullPath: '/settings/dashboard'
      preLoaderRoute: typeof SettingsDashboardRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/backup': {
      id: '/settings/backup'
      path: '/backup'
      fullPath: '/settings/backup'
      preLoaderRoute: typeof SettingsBackupRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archive': {
      id: '/settings/archive'
      path: '/archive'
      fullPath: '/settings/archive'
      preLoaderRoute: typeof SettingsArchiveRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/api/webhooks/battery': {
      id: '/api/webhooks/battery'
      path: '/api/webhooks/battery'
      fullPath: '/api/webhooks/battery'
      preLoaderRoute: typeof ApiWebhooksBatteryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsArchiveRoute: typeof SettingsArchiveRoute
  SettingsBackupRoute: typeof SettingsBackupRoute
  SettingsDashboardRoute: typeof SettingsDashboardRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsSyncRoute: typeof SettingsSyncRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchiveRoute: SettingsArchiveRoute,
  SettingsBackupRoute: SettingsBackupRoute,
  SettingsDashboardRoute: SettingsDashboardRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsSyncRoute: SettingsSyncRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ApiWebhooksBatteryRoute: ApiWebhooksBatteryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
